---
- name: Install NTP
  yum: pkg=ntp state=installed
  tags: ntp
      
- name: Config NTP
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify:
      - restart ntpd
      
- name: Make sure NTP is started up
  service: name=ntpd state=started enabled=yes
  tags: ntp
  
- name: Download EPEL repo
  get_url: dest=/tmp/epel-release.rpm  url={{ epel.repo }}

- name: Install EPEL repo
  yum: pkg=/tmp/epel-release.rpm state=installed

- name: Disable firewall
  action: service name=firewalld state=stopped enabled=false