---
    - name: Install nginx
      yum: name=nginx state=latest
      tags: nginx
    
    - name: Ensure nginx is running
      service: name=nginx state=started enabled=true
      tags: nginx

    - name: Copy nginx configuration
      template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/{{ project.name }}.conf
      tags: nginx
      notify: restart nginx

    - name: set SELinux to permissive
      action: selinux policy=targeted state=permissive