---
    - name: Install Python specific packages
      action: yum name={{ item }} state=present
      with_items:
        - python-devel
        - python-setuptools
      tags: python
      
    - name: Install virtualenv
      easy_install: name=virtualenv
      
    - name: Check if virtualenv for this project already exists
      stat: path=/env/{{ project.name }}/bin/
      register: venv_dir
      
    - name: Create virtualenv if needed
      command: virtualenv /env/{{ project.name }} --no-site-packages
               creates=/env/{{ project.name }}/bin/activate
      when: venv_dir.stat.isdir is not defined
      
    - name: Ensure virtualenv folder is owned by vagrant user
      file: path=/env/ owner=vagrant group=vagrant state=directory recurse=yes
      
    - name: Check if requirements file exists
      stat: path=/data/www/{{ project.name }}/requirements.txt
      register: requirements_file
      
    - name: Install project requirements
      pip: requirements=/data/www/{{ project.name }}/requirements.txt virtualenv=/env/{{ project.name }}
      environment:
          PATH: /usr/pgsql-9.3/bin:{{ ansible_env.PATH }}
      when: requirements_file.stat.exists